version: "3"

x-common: &common
  restart: always
  logging:
    options:
      max-size: "10m"
      max-file: "5"

services:
  watchtower:
    image: ${AWS_ECR_SERVICE_URL}/watchtower:${TAG:-latest}
    container_name: ap-watchtower
    environment:
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: ap-api
    <<: *common

  loki:
    image: grafana/loki:2.6.1
    container_name: ap-loki
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -config.expand-env=true
    <<: *common

  promtail:
    image: grafana/promtail:2.6.1
    container_name: ap-promtail
    command:
      - -config.file=/etc/promtail/config.yaml
      - -config.expand-env=true
    environment:
      - APP_API_LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./config/promtail-conf.yaml:/etc/promtail/config.yaml
      - logs:/var/log/app/
    <<: *common

  grafana:
    image: grafana/grafana:latest
    container_name: ap-grafana
    ports:
      - "3000:3000"
    <<: *common
