[tool.poetry]
name = "devopsiucourse"
version = "0.1.0"
description = ""
authors = ["Mark Nicholson <i@justmark0.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.2"
requests = "^2.28.1"
pytz = "^2022.2.1"
pytest = "^7.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
