[tool.poetry]
name = "app-python"
version = "0.1.0"
description = ""
authors = ["Dmitry Chermnykh <76gh6rvso@relay.firefox.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.81.0"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
pytz = "^2022.2.1"
gunicorn = "^20.1.0"
prometheus-fastapi-instrumentator = "^5.9.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
requests = "^2.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
