apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-app-helm.fullname" . }}
  labels:
    {{- include "python-app-helm.labels" . | nindent 4 }}
    release: service-bonus

spec:
  selector:
    matchLabels:
      {{- include "python-app-helm.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http