web_app_name: "app_python"
web_app_image:
  registry: "kamilakhamidullina"
  name: "devops_lab2"
  tag: "latest"
web_app_port:
  internal: 8000
  external: 80

web_app_base_path: "/opt/{{ web_app_name }}"

web_app_full_wipe: false