docker_apt_arch: '{{ ''arm64'' if ansible_architecture == ''aarch64'' else ''amd64'' }}'
docker_apt_gpg_key: '{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg'
docker_apt_ignore_key_error: true
docker_apt_release_channel: stable
docker_apt_repository: deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}
docker_compose_arch: '{{ ansible_architecture }}'
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present
docker_compose_path: /usr/local/bin/docker-compose
docker_compose_url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ docker_compose_arch }}
docker_compose_version: v2.11.1
docker_daemon_options: {}
docker_edition: ce
docker_install_compose: true
docker_install_compose_plugin: false
docker_packages:
  - docker-{{ docker_edition }}
  - docker-{{ docker_edition }}-cli
  - docker-{{ docker_edition }}-rootless-extras
  - containerd.io
docker_packages_state: present
docker_repo_url: https://download.docker.com/linux
docker_restart_handler_state: restarted
docker_service_enabled: true
docker_service_manage: true
docker_service_state: started
docker_users: []
docker_yum_gpg_key: '{{ docker_repo_url }}/centos/gpg'
docker_yum_repo_enable_nightly: "0"
docker_yum_repo_enable_test: "0"
docker_yum_repo_url: '{{ docker_repo_url }}/{{ (ansible_distribution == ''Fedora'') | ternary(''fedora'',''centos'') }}/docker-{{ docker_edition }}.repo'
