apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-python.fullname" . }}-configmap
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" | nindent 4 }}