apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-python.fullname" . }}-secret
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
