apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ include "python-app-helm.fullname" . }}-config
 labels:
   {{- include "python-app-helm.labels" . | nindent 4 }}
data:
 config.json: |-
   {{ .Files.Get "files/config.json" }}