apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timeweb.fullname" . }}-config
  labels:
    {{- include "timeweb.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" }}
