password: ENC[AES256_GCM,data:5WmZ1nML9fqj,iv:jS9276FkSxE1mLtiajlPxePezjtCiwUIW2Ll2it6X+s=,tag:CTY4gND19sPQgDeLdp5S4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-13T13:05:31Z"
    mac: ENC[AES256_GCM,data:rhQJkuvxq7FI9f6L1G76MV9z6+4AvRYBo5XQ6G0T/4uq//6p8dSA6DXi8CvdLcxjT7OQg+57OwxvMONDVwK11ul1ETMtx1V2l62AQKzGgiNct38hMclnqBfyIUW0nF4opfQtcdIcwcd0A5lDobdG4gjoTYroJJK6qGrNk9Ul/JQ=,iv:pVIGeEbZr2crodJ80300g+4jGPnwJCFREKldSLh8yx8=,tag:EG/DmEvBc3VuinpSd762pg==,type:str]
    pgp:
        - created_at: "2023-02-13T13:05:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYL1WqsocG9oSAQdAcnhS2wYoUZ9XFeM7oPl06BY9yPOjvdom1GBgMhMUWF0w
            e11B1K2/jAim1TjBJXLaS/2pKOO+AUUdFuSxP/5JG0KgJXZd+X21FcEGVDxy2+E
            1GgBCQIQ3JsbsyddIMsgbYQbmwnTLc4dCTRgpr8VKF532DqR5LWR8ql8TPduZyAh
            R+IcKA19dpFlEyjhqISjj/TWUcKXgc5YpE8LNzkxgd+tAtX2h57i3uMfDveNAUtt
            PeklFpJq2r39WA==
            =NeLG
            -----END PGP MESSAGE-----
          fp: AE668ED0EF173079125E99791158A5DABD0CD9A6
    unencrypted_suffix: _unencrypted
    version: 3.7.3