name: app_dart
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

assets:
  - packages/timezone/data/latest.tzf

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^4.3.0
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.4
  flutter_riverpod: ^1.0.4
  intl: ^0.17.0
  timezone: ^0.8.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0

flutter:

  uses-material-design: true
