global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'app_python'
    scrape_interval: 10s
    static_configs:
      - targets: ['app_python:8000']

  - job_name: 'app_rust'
    scrape_interval: 10s
    static_configs:
      - targets: ['app_rust:8000']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    scrape_interval: 10s
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    scrape_interval: 10s
    static_configs:
      - targets: ['promtail:9080']
