- name: Lab6 Python
  hosts: all
  roles:
    - name: web_app
      tags: [web_app-python]
      vars:
        web_app_name: app_python
        web_app_path: /app_python
        web_app_port: 5000
        web_container_port: 8080
        web_app_image: docker.io/chermnyx/inno-devops-python
