apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: default
type: Opaque
data:
#  username: {{ .Values.username | b64enc | quote }}
#  password: {{ .Values.password | b64enc | quote }}
