global:
    scrape_interval:     10s
    evaluation_interval: 5s

scrape_configs:
  - job_name: app_python
    static_configs:
      - targets: ['app_python:5000']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: promtail
    static_configs:
      - targets: ['promtail:9080']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
