apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moscow-time.fullname" . }}-config
  labels:
    {{- include "moscow-time.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" }}