apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-python.fullname" . }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ include "app-python.fullname" . }}
  endpoints:
  - interval: 5s
    port: http