apiVersion: v1
kind: Service
metadata:
  name: app-rust-server-service
spec:
  selector:
    app: app-rust-server
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000
  type: LoadBalancer