apiVersion: v1
kind: ConfigMap
metadata:
  name: app-python-config
  labels:
    app: app-python
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
data:
  config.json:
    '{{ .Files.Get "files/config.json"}}'