name: Java check
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  check_changes:
    runs-on: [ubuntu-latest]
    name: Check changes in javascript app
    outputs:
      status: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            app_javascript/**
  build:
    needs: check_changes
    runs-on: [ubuntu-latest]
    if: needs.check_changes.outputs.status == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: |
          npm install -g npm@latest
          npm cache clean --force
          npm rm -rf node_modules && rm package-lock.json
          npm install
      - name: Run
        run: |
          npm run build --if-present
  build_push:
    needs: check_changes
    runs-on: [ubuntu-latest]
    if: needs.check_changes.outputs.status == 'true'
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: app_javascript/app_js/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_java:latest
