name: Run tests on push
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  check_changes:
    runs-on: [ubuntu-latest]
    name: Check changes in app_python
    outputs:
      status: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            app_python/**
  run_tests:
    needs: check_changes
    runs-on: [ubuntu-latest]
    if: needs.check_changes.outputs.status == 'true'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r app_python/requirements.txt
      - name: flake8 Linter
        uses: py-actions/flake8@v2
      - name: Run tests
        run: coverage run app_python/src/test.py
      - name: Tests report
        run: coverage report
  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:app_python app_python
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:app_python