name: Python  Snyk
on: push
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      flutter: ${{ steps.filter.outputs.flutter }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          python:
            - 'app_python/**'
          flutter:
            - 'app_flutter/**'

  security:
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f app_python/requirements.txt ]; then pip install -r app_python/requirements.txt; fi
      - name: Run Snyk to check for vulnerabilities
        working-directory: app_python
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}