name: Rust

on:
  push:
    branches:
      - 'lab*'
      - $default-branch
    paths:
      - 'app_rust/**'
      - '.github/rust**'
  pull_request:
    branches:
      - $default-branch 
    paths:
      - 'app_rust/**'
      - '.github/rust**'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  security-events: write

jobs:
  checks:

    # To avoid multiple runs on single commit
    # It is still checked by push trigger, so no worries.
    if: "!(contains(github.head_ref, 'lab') == true && endsWith(github.base_ref, 'master'))"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_rust

    steps:
    - uses: actions/checkout@v3
    # It's better configured for rust thus not default
    - uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true
    - name: Code style check
      run: cargo fmt --all --verbose --check
    - name: Build
      run: cargo check
    - name: Run tests
      run: cargo test --verbose
    - run: rustup component add clippy
    - name: Run clippy check
      run: cargo clippy --all-features -- -D warnings
