name: terraform

on: 
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get -qq update
          sudo apt-get -qq install terraform

      - name: Terraform linter for docker
        working-directory: terraform/docker
        run: |
          terraform fmt -check

      - name: Terraform linter for github
        working-directory: terraform/github
        run: |
          terraform fmt -check

      - name: Terraform linter for yandex
        working-directory: terraform/yandex
        run: |
          terraform fmt -check
